---
title: "01-30-24 warmup"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(janitor)
```
## load bison data
```{r}
bison <- read_csv("data/bison.csv")
```
## find dimesnions
```{r}
glimpse(bison)
dim(bison)
```


```{r}
names(bison)
```

#filter data 
```{r}
bison_subset <- select(bison, "data_code", "animal_sex", "animal_weight","animal_yob")
```

#filter animals born between 1980-1990
```{r}
bison_age <- filter(bison_subset, animal_yob>=1980 & animal_yob<=1990)
```

#how many males and females 
```{r}
bison_male <- filter(bison_age, animal_sex == "M")
bison_female <- filter(bison_age, animal_sex =="F")
```


## get the number of males and females 
```{r}
table(bison_age$animal_sex)
```

```{r}
dim(bison_male)
dim(bison_female)
```

there are 21 males and 414 females 

## are males or females bigger 
```{r}
mean(bison_female$animal_weight)
mean(bison_male$animal_weight)
```

on average, bison males are larger between 1980-1990