---
title: "lab 3 warm-up"
output: html_document
date: "2024-01-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 1. Plant Height Vector
```{r}
plant_height <- c(30.7, 37.6, 28.4, NA, 33.2)
```

### 2. Plant weight vector
```{r}
plant_weight <- c(4, 5.2, 3.7, NA, 4.6)
```

### 3. Label for data matrix 
```{r}
samples <- c("Plant_1", "Plant_2", "Plant_3", "Plant_4", "Plant_5")
measured <- c("height", "weight")
```

### 4. combine data for height and weight
```{r}
plant_experiment <- c(plant_height, plant_weight)
```

### 5. build data matrix (False builds it from top to bottom, T will fill left to right)
```{r}
plant_experiment_matrix <- matrix(plant_experiment, nrow=5, byrow=F)
plant_experiment_matrix
```

### 6. Name columns and rows
```{r}
colnames(plant_experiment_matrix) <- measured
rownames(plant_experiment_matrix) <- samples
plant_experiment_matrix
```
### 7. Calcuate means of each colums
```{r}
plant_means <- colMeans(plant_experiment_matrix, na.rm=T)
plant_means
```

### Add this as a new row
```{r}
plant_experiment_matrix_final <- rbind(plant_experiment_matrix, plant_means)
plant_experiment_matrix_final
```


